/* AUTO-GENERATED by scripts/build-ga-windows.mjs — do not edit by hand.
 * Source: ABC Gardening Australia Vegie Guide, monthly planting lists per zone
 * (https://www.abc.net.au/gardening/vegie-guide-zones/9796680), captured 2026-09-24.
 * Zone mapping: GA Temperate → warm-temperate, GA Cool → cool-temperate.
 * These months are when GA lists the crop as suitable to plant/sow.
 */
import type { ClimateZoneId, Month } from '../domain/types';

export const GA_WINDOWS: Record<string, Partial<Record<ClimateZoneId, Month[]>>> = {
  "basil": {
    "tropical": [1, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 8, 9, 10, 11, 12],
    "warm-temperate": [9, 10, 11, 12],
    "cool-temperate": [1, 9, 10, 11, 12],
    "arid": [1, 3, 8, 9, 10, 11, 12]
  },
  "bean-bush": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 9, 10, 11, 12],
    "cool-temperate": [1, 10, 11, 12],
    "arid": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "bean-climbing": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 9, 10, 11, 12],
    "cool-temperate": [1, 10, 11, 12],
    "arid": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "beetroot": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 9, 10, 11, 12],
    "arid": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "cabbage": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "warm-temperate": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "arid": [3, 4, 5, 6, 7, 8, 9, 10]
  },
  "capsicum": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [9, 10, 11, 12],
    "cool-temperate": [10, 11],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "chilli": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [9, 10, 11, 12],
    "cool-temperate": [2, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "chives": {
    "tropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 7, 8, 9, 10, 11, 12]
  },
  "eggplant": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [9, 10, 11, 12],
    "cool-temperate": [10, 11, 12],
    "arid": [1, 2, 3, 8, 9, 10, 11, 12]
  },
  "potato": {
    "tropical": [1, 3, 4, 5, 6, 7, 8, 9, 10, 12],
    "subtropical": [8, 9, 10],
    "warm-temperate": [2, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 10, 11, 12],
    "arid": [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "radish": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "sunflower": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 10, 11, 12],
    "cool-temperate": [11, 12],
    "arid": [1, 2, 3, 4, 9, 10, 11, 12]
  },
  "sweet-corn": {
    "tropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 10, 11, 12],
    "cool-temperate": [1, 10, 11, 12],
    "arid": [1, 2, 3, 9, 10, 11, 12]
  },
  "carrot": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "subtropical": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 9, 10, 11, 12],
    "arid": [2, 3, 4, 5, 6, 7, 8, 9, 10]
  },
  "cucumber": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 9, 10, 11, 12],
    "cool-temperate": [2, 10, 11, 12],
    "arid": [1, 2, 3, 8, 9, 10, 11, 12]
  },
  "leek": {
    "tropical": [2, 3, 4, 7],
    "subtropical": [1, 2, 3],
    "warm-temperate": [1, 3, 4, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 10, 11, 12],
    "arid": [2, 3, 4, 5, 6, 7]
  },
  "lettuce": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "subtropical": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "pumpkin": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9],
    "subtropical": [1, 2, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 9, 10, 11, 12],
    "cool-temperate": [10, 11],
    "arid": [1, 2, 3, 8, 9, 10, 11, 12]
  },
  "silverbeet": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9],
    "subtropical": [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "tomato": {
    "tropical": [2, 3, 4, 5, 6, 7, 8],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [2, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "cherry-tomato": {
    "tropical": [2, 3, 4, 5, 6, 7, 8],
    "subtropical": [1, 2, 3, 4, 8, 9, 10, 11, 12],
    "warm-temperate": [2, 8, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 9, 10, 11, 12],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "zucchini": {
    "tropical": [2, 3, 4, 5, 6, 7, 8, 9],
    "subtropical": [1, 2, 3, 8, 9, 10, 11, 12],
    "warm-temperate": [2, 9, 10, 11, 12],
    "cool-temperate": [10, 11, 12],
    "arid": [1, 2, 3, 8, 9, 10, 11, 12]
  },
  "broad-bean": {
    "tropical": [3, 4, 5, 6],
    "subtropical": [3, 4, 5, 6],
    "warm-temperate": [3, 4, 5, 6, 7],
    "cool-temperate": [3, 4, 5, 6, 7, 8],
    "arid": [3, 4, 5, 6]
  },
  "cauliflower": {
    "tropical": [3, 4, 5],
    "subtropical": [3, 4, 7],
    "warm-temperate": [3, 4],
    "cool-temperate": [3, 4, 8, 9],
    "arid": [3, 4, 5, 6]
  },
  "kale": {
    "tropical": [3, 4, 5, 6, 7, 8],
    "subtropical": [3, 4, 5, 6, 7, 9],
    "warm-temperate": [2, 3, 4, 9, 10, 11],
    "cool-temperate": [1, 2, 3, 4, 5, 6],
    "arid": [3, 4, 5, 6, 7, 9]
  },
  "onion": {
    "tropical": [3, 4, 5, 6],
    "subtropical": [2, 3, 4, 5, 6, 7],
    "warm-temperate": [2, 3, 4, 6, 7, 8],
    "cool-temperate": [3, 4, 8, 9, 10, 11],
    "arid": [2, 3, 4, 5, 6, 7]
  },
  "broccoli": {
    "tropical": [4, 5, 6],
    "subtropical": [2, 3, 4, 5],
    "warm-temperate": [1, 2, 3, 4, 9, 10, 11, 12],
    "cool-temperate": [1, 4, 5, 6, 7, 8],
    "arid": [2, 3, 4, 5, 6, 7]
  },
  "coriander": {
    "tropical": [4, 5, 6, 7, 8, 9],
    "subtropical": [9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 9, 10, 11, 12],
    "arid": [3, 9, 10, 11, 12]
  },
  "garlic": {
    "tropical": [4, 5, 6, 7, 11],
    "subtropical": [4, 5, 6, 7],
    "warm-temperate": [4, 5, 6, 7, 8, 9, 10],
    "cool-temperate": [7, 8],
    "arid": [3, 4, 5, 6, 7]
  },
  "parsley": {
    "tropical": [4, 5, 6, 7, 8, 9],
    "subtropical": [2, 3, 4, 5],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 3, 9, 10, 11, 12],
    "arid": [2, 3, 4, 5]
  },
  "rocket": {
    "tropical": [4, 5, 6, 7, 9],
    "subtropical": [3, 4, 5, 6, 7, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "arid": [1, 3, 4, 5, 6, 7, 9, 10, 11, 12]
  },
  "oregano": {
    "tropical": [5, 6, 7, 8],
    "subtropical": [1, 2, 3, 4, 9, 10, 11, 12],
    "warm-temperate": [1, 2, 3, 4, 5, 9, 10, 11, 12],
    "cool-temperate": [1, 2, 9, 10, 11, 12],
    "arid": [1, 2, 3, 9, 10, 11, 12]
  },
  "pak-choy": {
    "tropical": [5, 6],
    "subtropical": [3, 4, 5],
    "warm-temperate": [2, 3, 4, 5, 9, 10],
    "cool-temperate": [3, 9, 10, 11, 12],
    "arid": [3, 4, 5]
  },
  "sweet-potato": {
    "tropical": [7, 9, 10, 11],
    "subtropical": [9, 10, 11, 12],
    "warm-temperate": [2],
    "arid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  },
  "warrigal-greens": {
    "tropical": [7, 8, 9],
    "subtropical": [9, 10, 11],
    "warm-temperate": [1, 2, 10, 11, 12],
    "cool-temperate": [1, 2, 10, 11, 12],
    "arid": [1, 3, 9, 10, 11, 12]
  },
  "pea": {
    "tropical": [9],
    "subtropical": [4, 5, 6, 7],
    "warm-temperate": [2, 4, 5, 6, 7, 8, 9, 12],
    "cool-temperate": [4, 5, 6, 7, 8, 9],
    "arid": [3, 5, 6, 7]
  },
  "spinach": {
    "subtropical": [4, 5, 6, 11],
    "warm-temperate": [2, 3, 4, 5, 8, 9],
    "cool-temperate": [3, 4, 5, 6, 7, 8],
    "arid": [3, 4, 5, 6, 7]
  },
  "spring-onion": {
    "subtropical": [7, 8, 9],
    "warm-temperate": [2, 8, 10],
    "cool-temperate": [9, 10, 11, 12],
    "arid": [3, 5, 7, 8, 9]
  }
} as Record<string, Partial<Record<ClimateZoneId, Month[]>>>;
